# /etc/ansible/roles/wls_basic_config/tasks/main.yml
 
- name: create create_basic_domain.py
  template:
    src=roles/common/templates/weblogic/create_basic_domain_py.j2 
    dest="{{ create_basic_domain_py }}"
    #owner="{{ oracle_install_user }}"
    #group="{{ oracle_install_group }}"
    #mode=0644
    
- name: create basic domain
  become_user: "{{ oracle_install_user }}"
  shell: "{{ wlst_sh }} -loadProperties {{ environment_properties }} {{ create_basic_domain_py }}"
  args:
    creates="{{ config_xml }}"
    
- name: create application home directory
  file:
    path="{{ domain_application_home }}"
    state=directory
    owner="{{ oracle_install_user }}"
    group="{{ oracle_install_group }}"
    mode=0755

- name: create nodemanager home directory
  file:
    path="{{ node_manager_home }}"
    state=directory
    owner="{{ oracle_install_user }}"
    group="{{ oracle_install_group }}"
    mode=0755
    
- name: create nodemanager bin directory
  file:
    path="{{ node_manager_home }}/bin"
    state=directory
    owner="{{ oracle_install_user }}"
    group="{{ oracle_install_group }}"
    mode=0755
    
- name: create domain configuruation home directory
  file:
    path="{{ domain_configuration_home }}"
    state=directory
    owner="{{ oracle_install_user }}"
    group="{{ oracle_install_group }}"
    mode=0755
    
- name: create domain configuruation bin directory
  file:
    path="{{ domain_configuration_home }}/bin"
    state=directory
    owner="{{ oracle_install_user }}"
    group="{{ oracle_install_group }}"
    mode=0755
    
- name: create nodemanager.properties
  template:
    src=roles/common/templates/weblogic/nodemanager_properties.j2 
    dest="{{ node_manager_properties }}"
    owner="{{ oracle_install_user }}"
    group="{{ oracle_install_group }}"
    mode=0644
    
- name: create setUserOverrides.sh
  template:
    src=roles/common/templates/weblogic/set_user_overrides_sh.j2 
    dest="{{ set_user_overrides_sh }}"
    owner="{{ oracle_install_user }}"
    group="{{ oracle_install_group }}"
    mode=0744
    
- name: create nodemanager init script
  template:
    src=roles/common/templates/weblogic/nodemanager.j2 
    dest="{{ node_manager_service }}"
    owner="{{ oracle_install_user }}"
    group="{{ oracle_install_group }}"
    mode=0744
    
- name: enable and start nodemanager service
  service:
    name=nodemanager
    state=started
    enabled=yes
  register: nodemanager_started
    
- name: start admin server
  become_user: "{{ oracle_install_user }}"
  shell: "nohup {{ admin_server_start_service }}"
  args:
    creates="{{ admin_server_lock_file }}"
  when: nodemanager_started|success
