 
- name: create deploy_environment.py
  sudo: true
###  become_user: root
###  become_user: "{{ oracle_user }}"
  template:
    src: roles/wls_deploy_applications/templates/deploy_environment_py_j2 
    dest: "{{ deploy_environment_py }}"
###    dest: "/tmp/apa"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0644
  register: deploy_environment_py_created

- name: create directory for applications
  sudo: true
  file: path="{{ domain_application_home }}" state=directory owner={{ oracle_user }} group={{ oracle_group }} recurse=yes
 
- name: copy deployment artifacts
  sudo: true
  copy:
    src=roles/common/files/weblogic/deploy/
    dest="{{ domain_application_home }}"
    owner="{{ oracle_user }}"
    group="{{ oracle_group }}"
  register: deployment_artifacts_copied
 
- name: debug registered values
  debug: 
    var={{ item }}
  with_items:
    - deploy_environment_py_created
    - deployment_artifacts_copied
 
- name: (un)deploy applications
  sudo: true
  shell: "id; {{ wlst_sh }} -loadProperties {{ environment_properties }} {{ deploy_environment_py }}"
  when: deploy_environment_py_created.changed or deployment_artifacts_copied.changed

