---
# ==> Ansible Role for configure, start and autostart on reboot Node manager
# ==> for a WebLogic 12c R2 Domain
- name: Fetch files
  fetch:
   src: "{{ domain_home }}/nodemanager/nodemanager.properties"
   dest: /tmp/nm-fore-copy-{{ inventory_hostname }}
   flat: yes
   fail_on_missing: no

# Vi använder och utgår från den fil som följer med installationen
#####- name: Copy Nodemanager Properties file
#####  template: src=nodemanager.properties dest={{ domain_home }}/nodemanager/ owner={{ oracle_user }} group={{ oracle_group }}
#####  tags:
#####    - start-nodemanager
#####

- name: Change the ListenAddress to be in line whith our configuration.
  lineinfile:
    dest: "{{ domain_home }}/nodemanager/nodemanager.properties"
    regexp: "^ListenAddress="
    line: "ListenAddress={{ node_manager_hostname }}"

- name: Change the ListenPort to be in line whith our configuration.
  lineinfile:
    dest: "{{ domain_home }}/nodemanager/nodemanager.properties"
    regexp: "^ListenPort="
    line: "ListenPort={{ node_manager_port }}"

- name: Change the NMType to be in line whith our configuration.
  lineinfile:
    dest: "{{ domain_home }}/nodemanager/nodemanager.properties"
    regexp: "^ListenPort="
    insertafter: "^ListenPort="
    line: "NMType={{ node_manager_type }}"

- name: Fetch files
  fetch:
   src: "{{ domain_home }}/nodemanager/nodemanager.properties"
   dest: /tmp/nm-efter-copy-{{ inventory_hostname }}
   flat: yes
   fail_on_missing: no

# ==> Create startup script for nodemanager
- name: Copy nodemanager systemd script
  template: src=nodemanager.service dest=/etc/systemd/system/ mode=0664
  tags:
    - start-nodemanager

- name: Enable nodemanager as linux service
  command: 'systemctl enable nodemanager'
  tags:
    - start-nodemanager

- name: Start Node Manager
  command: 'systemctl start nodemanager'
  tags:
    - start-nodemanager

- name: Waiting for nodemanager to come up
  wait_for: port={{ node_manager_port }} host={{ node_manager_address }} delay=5 timeout=90
  tags:
    - start-nodemanager

- name: Fetch files
  fetch:
   src: "{{ domain_home }}/nodemanager/nodemanager.properties"
   dest: /tmp/nm-efter-start-{{ inventory_hostname }}
   flat: yes
   fail_on_missing: no

#####Available from 2.3, running on 2.2.1
#####- name: Backup of Nodemanager files
#####   archive: 
#####    path: "{{ domain_home }}/nodemanager"
#####    dest: /tmp/nm.tgz
#####  tags:
#####    - start-nodemanager
