---
- name: Fetch files
  fetch:
   src: "{{ domain_home }}/nodemanager/nodemanager.properties"
   dest: /tmp/ms-fore-start-{{ inventory_hostname }}
   flat: yes
   fail_on_missing: no

# ==> Copy library extensions 
- name: copy library extensions
  sudo: true
  copy:
    src="roles/common/files/weblogic/lib/"
    dest="{{ domain_extension_home }}"
    owner="{{ oracle_user }}"
    group="{{ oracle_group }}"
  register: extension_lib_copied

# ==> Create managed server on Domain

- name: Copy create managed server script
  template: src=create-managed.py dest={{ mw_installer_folder }}

- name: Copy create GenBootStartupProps server script
  template: src=create-genboot.py.j2 dest={{ mw_installer_folder }}/create-genboot.py

- name: Execute create managed server script
  shell: '{{middleware_common_home }}/common/bin/wlst.sh {{ mw_installer_folder }}/create-managed.py'
    
- name: Create security folder for managed server
  file: state=directory path={{ domains_home }}/{{ domain_name }}/servers/{{ managed_server_name }}/security
