---

- name: disable selinux
  selinux:
    state=disabled
#
# Thomas Hjert: iptables används ej
#    
- name: disable firewalld
  service:
    name=firewalld
    state=stopped
    enabled=no
 
- name: install packages
  become_user: root
  become_method: sudo
  yum:
    name={{ item }}
    state=present
  with_items:
    - binutils
    - compat-libcap1
    - compat-libstdc++-33
    - gcc
    - gcc-c++
    - glibc
    - glibc-devel
    - libaio
    - libaio-devel
    - libgcc
    - libstdc++
    - libstdc++-devel
    - make
    - openmotif
    - sysstat
    - net-tools
    - ntpdate
    - ntp
##
## Thomas Hjert Fanns inget sådant paket
##    
##    - openmotif22

- name: Make sure ntpdate service is running
  systemd: state=started name=ntpdate

- name: create group
  group:
    name={{ oracle_install_group }}
    gid={{ oracle_install_group_id }}
    state=present
    
- name: create user
  user:
    name={{ oracle_install_user }}
    state=present
    createhome=yes
    group={{ oracle_install_group_id }}
    password={{ oracle_install_password }}
    
- template: 
    src=roles/common/templates/linux/sysctl_conf.j2 
    dest=/etc/sysctl.conf
    owner=root
    group=root
    mode=0644
    
- template: 
    src=roles/common/templates/linux/limits_conf.j2 
    dest=/etc/security/limits.conf
    owner=root
    group=root
    mode=0644

- name: create temporary software directory
  file:
    path="{{ software_directory }}"
    state=directory
    owner="{{ oracle_install_user }}"
    group="{{ oracle_install_group }}"
    mode=0755
    recurse=yes

- name: create temporary templates directory
  file:
    path="{{ templates_directory }}"
    state=directory
    owner="{{ oracle_install_user }}"
    group="{{ oracle_install_group }}"
    mode=0755
    recurse=yes


- copy:
    src: "{{ software_directory }}/{{ weblogic_file_name }}"
    dest: "{{ software_directory }}/{{ weblogic_file_name }}"
    owner: root
    group: root
    mode: 0644

- copy:
    src: "{{ software_directory }}/{{ jvm_file_name }}"
    dest: "{{ software_directory }}/{{ jvm_file_name }}"
    owner: root
    group: root
    mode: 0644
