# /etc/ansible/roles/wls_deploy_config/tasks/main.yml
 
- name: create create_deployment_environment.py
  template:
    src=roles/common/templates/weblogic/create_deployment_environment_py.j2 
    dest="{{ create_deploy_domain_py }}"
    owner="{{ oracle_install_user }}"
    group="{{ oracle_install_group }}"
    mode=0644
    
- name: create deployment environment
  become_user: "{{ oracle_install_user }}"
  shell: "{{ wlst_sh }} -loadProperties {{ environment_properties }} {{ create_deploy_domain_py }}"
  args:
    creates="{{ domain_configuration_home }}/config/deploy_config.txt"
    
- name: create template
  become_user: "{{ oracle_install_user }}"
  shell: "{{ pack_sh }} -managed=true -domain={{ domain_configuration_home }} -template={{ wls_template_file }} -template_name={{ domain_name }}"
  args:
    creates="{{ wls_template_file }}"
###  shell: "{{ pack_sh }} -managed=true -domain={{ domain_configuration_home }} -template=/u01/app/oracle/weblogic12.1.3/installation/wlserver/common/templates/wls/wls.jar -template_name={{ domain_name }}"


###- file:
###    path: /mnt/hgfs/wls_temp/tryout_domain.jar
###    mode: 0777
###
###- fetch:
###    src: /mnt/hgfs/wls_temp/tryout_domain.jar
###    dest: /tmp
###    #flat: yes
###    fail_on_missing: yes
