---
- name: Define variables and deploy applications
  hosts: weblogic
  sudo: True
  vars_files:
    # User defined variables for infrastructure
    - infra-vars.yml
    - wls-vars.yml
    - secrets.yml
    - deployment-vars.yml
  roles:
    - common
    - wls-stop-nodemanager
###  become_user: "{{ oracle_user }}"
###  become_user: root
