- name: Start Node Manager
  ###become_user: root
  ###become_method: sudo
  sudo: True
  command: 'systemctl start nodemanager'
  tags:
    - start-nodemanager

- name: Waiting for nodemanager to come up
  wait_for: port={{ node_manager_listen_port }} delay=5 timeout=90
