# ==> Ansible Role for start Admin Server for the first time in a configured
# ==> WebLogic 12c R2 Domain

- name: Distribute installSvcMS.cmd based on template where delay=12000 is added
  win_template: src=installSvcMS.cmd.j2 dest={{ oracle_base }}/server/bin/installSvcMS.cmd owner={{ oracle_user }} group={{ oracle_group }}
  tags:
    - start-admin-server

- name: Distribute removeManagedServerService.cmd based on template (New file to setup AdminServer as a service)
  win_template: src=removeManagedServerService.cmd.j2 dest={{ oracle_base }}/server/bin/removeManagedServerService.cmd owner={{ oracle_user }} group={{ oracle_group }}
  tags:
    - start-admin-server

- name: Execute removeManagedServerService.cmd that will create the service
  win_shell: "{{ oracle_base }}/server/bin/removeManagedServerService.cmd > {{ oracle_base }}/logs/removeManagedServerService_{{ domain_name }}.log"
  tags:
     - start-admin-server

- name: Distribute addManagedServerService.cmd based on template (New file to setup AdminServer as a service)
  win_template: src=addManagedServerService.cmd.j2 dest={{ oracle_base }}/server/bin/addManagedServerService.cmd owner={{ oracle_user }} group={{ oracle_group }}
  tags:
    - start-admin-server

- name: Execute addManagedServerService.cmd that will create the service
  win_shell: "{{ oracle_base }}/server/bin/addManagedServerService.cmd > {{ oracle_base }}/logs/addManagedServerService_{{ domain_name }}.log"
  tags:
     - start-admin-server
